name: Sarthi
description: Easy to setup Docker based empheral previews!
author: Tushar Gupta

branding:
  icon: check
  color: blue

runs:
  using: docker
  image: Dockerfile

inputs:
  sarthi_server_url:
    required: true
    description: 'URL of the deployed sarthi server'
  compose_file:
    description: 'Name of docker compose file in your project'
    default: docker-compose.yml
  sarthi_secret:
    required: true
    description: Secret text for authentication
  fork_repo_url:
    description: 'GitHub URL of Head Repo when a PR is created, default empty for push events'
    default: ${{github.event.pull_request.head.repo.full_name}}
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
