version: "3"

services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: sarthi_nginx
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx-confs:/etc/nginx/conf.d

  sarthi:
    build: .
    restart: always
    volumes:
      # hack to bypass file resource sharing error
      # not tested and no support for windows server 💩
      - ./deployments:${DEPLOYMENTS_MOUNT_DIR:-/deployments}
      - ./nginx-confs:${NGINX_PROXY_CONF_LOCATION:-/nginx-confs}
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DEPLOYMENTS_MOUNT_DIR: ${DEPLOYMENTS_MOUNT_DIR}
      NGINX_PROXY_CONF_LOCATION: ${NGINX_PROXY_CONF_LOCATION}
      ENV: ${ENV:-local}
      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_BASE_URL: ${VAULT_BASE_URL:-http://vault:8200}
      SECRET_TEXT: ${SECRET_TEXT}
    depends_on:
      - vault

  vault:
    image: vault:1.12.3
    restart: always
    ports:
      - "8200:8200"
    volumes:
      - ./vault/vault.json:/vault/config/vault.json
      - vault-secrets-dev:/vault/file
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_API_ADDR: http://0.0.0.0:8200
      VAULT_ADDRESS: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider http://127.0.0.1:8200/v1/sys/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  vault-secrets-dev:
