version: "3"

services:
  nginx:
    image: nginx:1.26.0
    restart: always
    container_name: sarthi_nginx
    ports:
      - "${PORT_NGINX:-80}:80" # Modified: Port number made variable
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx-confs:/etc/nginx/conf.d
      - ./sarthi.conf:/etc/nginx/conf.d/sarthi.conf
    depends_on:
      - portainer
      - vault
      - sarthi
      - grafana

  sarthi:
    build: .
    restart: always
    volumes:
      - ./deployments:${DEPLOYMENTS_MOUNT_DIR:-/deployments}
      - ./nginx-confs:${NGINX_PROXY_CONF_LOCATION:-/nginx-confs}
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DEPLOYMENTS_MOUNT_DIR: ${DEPLOYMENTS_MOUNT_DIR}
      NGINX_PROXY_CONF_LOCATION: ${NGINX_PROXY_CONF_LOCATION}
      ENV: ${ENV:-local}
      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_BASE_URL: ${VAULT_BASE_URL:-http://vault:8200}
      SECRET_TEXT: ${SECRET_TEXT}
    depends_on:
      - vault

  loki:
    image: grafana/loki:2.9.5
    restart: always
    ports:
      - "${PORT_LOKI:-3100}:3100" # Modified: Port number made variable
    volumes:
      - ./logging-config/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    depends_on:
      - promtail

  promtail:
    image: grafana/promtail:main-8978ecf
    restart: always
    volumes:
      - /var/log:/var/log
      - ./logging-config/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:10.1.10-ubuntu
    restart: always
    ports:
      - "${PORT_GRAFANA:-3000}:3000" # Modified: Port number made variable
    volumes:
      - grafana:/var/lib/grafana
      - ./logging-config/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./logging-config/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - loki

  vault:
    image: hashicorp/vault:1.16
    restart: always
    volumes:
      - ./vault/vault.json:/vault/config/vault.json
      - vault-secrets:/vault/file
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_API_ADDR: http://0.0.0.0:8200
      VAULT_ADDRESS: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider http://127.0.0.1:8200/v1/sys/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  portainer:
    image: portainer/portainer-ce:2.20.2
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  grafana:
  portainer_data:
  vault-secrets:
