name: Testing

on:
  push:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Testing the action
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run action
        uses: ./action
        with:
          name: 'John'